#!/usr/bin/env node

var fs = require('fs');
var path = require('path');

process.env["PWD"] = process.cwd();

var project_dirname = process.env['PWD'];
var local_runner = path.join(project_dirname, 'node_modules', 'closure-runner');

var runner_module = 'closure-runner';
if (fs.existsSync(local_runner)) {
  runner_module = local_runner;
}

var ClosureRunner = require(runner_module);
ClosureRunner.run(function (err) {
  if (err) {
    console.log(err.stack || err.message || err);
    process.exit(1);
  }
});
